"use client";
import { useMemo, useState } from "react";
type Question={text:string;hint:string}; type Level="Starter"|"Elementary"|"Intermediate"|"Advanced";
const levelNotes:Record<Level,string>={Starter:"Very short, familiar questions with answer support",Elementary:"Everyday topics and simple reasons",Intermediate:"Experiences, explanations, and opinions",Advanced:"Values, abstract ideas, and extended discussion"};
const templates:Record<Level,Array<[string,string]>>={
Starter:[["What {topic} do you like best?","You can say: I like ___ best."],["Do you like {topic}?","Answer yes or no, and add one reason."],["What color do you think of when you hear “{topic}”?","You can say: I think of ___."],["Is {topic} important to you?","You can say: Yes, because ___ / No, because ___."],["Who do you talk to about {topic}?","Think of a friend, family member, or teacher."],["When do you enjoy {topic}?","Try: in the morning, after class, or on weekends."],["Where can you find {topic}?","Name one place."],["Choose three words about {topic}.","For example: fun, useful, or difficult."],["What is one good thing about {topic}?","Begin with: One good thing is ___."],["Draw or describe your favorite {topic}.","Use simple adjectives such as big, small, new, or beautiful."]],
Elementary:[["What do you like most about {topic}, and why?","Give one clear reason."],["When did you first become interested in {topic}?","Say when, where, or who introduced it to you."],["How is {topic} part of your daily life?","Describe one habit or example."],["Would you recommend {topic} to a friend?","Explain why or why not."],["What is easy or difficult about {topic}?","Choose one point and explain it."],["Who has influenced your ideas about {topic}?","It can be someone you know or someone famous."],["What would you like to try related to {topic}?","Say what, where, and when."],["How is {topic} different now from the past?","Give one simple comparison."],["What is your best memory connected to {topic}?","Describe what happened and how you felt."],["What advice would you give someone new to {topic}?","Use: You should… / You shouldn’t…"]],
Intermediate:[["How has {topic} influenced your life or thinking?","Describe a specific example or experience."],["What is commonly misunderstood about {topic}?","Explain the misunderstanding and your view."],["What are the advantages and disadvantages of {topic}?","Discuss at least one point on each side."],["How might {topic} change in the next ten years?","Make a prediction and give your reason."],["What personal experience shaped your opinion of {topic}?","Tell the story briefly, then explain its effect."],["Should schools discuss {topic} more often?","State your position and support it with an example."],["How does culture affect the way people see {topic}?","Compare two places, groups, or generations."],["What problem related to {topic} deserves more attention?","Explain who it affects and why it matters."],["If you could change one thing about {topic}, what would it be?","Describe the change and its likely result."],["What can people learn from {topic}?","Connect your answer to real life."]],
Advanced:[["What principles should guide our decisions about {topic}?","Identify a value, then test it with an example."],["How has your understanding of {topic} evolved over time?","Contrast an earlier belief with your present view."],["When do individual freedom and social responsibility conflict in {topic}?","Consider both perspectives before giving your position."],["What assumptions about {topic} should we question?","Name an assumption and explain its consequences."],["To what extent is {topic} shaped by culture rather than personal choice?","Use a comparison or counterexample."],["What would a fair approach to {topic} look like?","Define fairness in this context and apply it."],["Which lifelong principle most strongly influences your view of {topic}?","Explain the principle and how it guides your actions."],["How should we balance tradition and change when considering {topic}?","Give one argument for each side."],["What important question about {topic} is rarely asked?","State the question and explain why it matters."],["Can disagreement about {topic} be productive?","Describe the conditions that make disagreement useful or harmful."]]
};
function makeQuestions(topic:string,level:Level,count:number):Question[]{const subject=topic.trim()||"this topic",source=templates[level];return Array.from({length:count},(_,i)=>{const [text,hint]=source[i%source.length];return{text:text.replaceAll("{topic}",subject),hint}})}
function parseRoster(value:string){return value.split(/[\n,]+/).map(n=>n.trim()).filter(Boolean)}
export default function TeacherPage(){
const[title,setTitle]=useState("Conversation Scavenger Hunt"),[topic,setTopic]=useState("personal interests"),[level,setLevel]=useState<Level>("Elementary"),[studentCount,setStudentCount]=useState(40),[variety,setVariety]=useState(10),[mode,setMode]=useState<"number"|"roster">("number"),[rosterText,setRosterText]=useState(""),[questions,setQuestions]=useState<Question[]>(()=>makeQuestions("personal interests","Elementary",10)),[publishing,setPublishing]=useState(false),[publishedUrl,setPublishedUrl]=useState(""),[error,setError]=useState("");
const roster=useMemo(()=>parseRoster(rosterText),[rosterText]),actualStudents=mode==="roster"?roster.length:studentCount;
const updateQuestion=(index:number,field:keyof Question,value:string)=>setQuestions(items=>items.map((item,i)=>i===index?{...item,[field]:value}:item));
async function publish(){setError("");if(!title.trim()||!questions.length||actualStudents<1){setError("Please add a title, at least one student, and at least one question.");return}setPublishing(true);try{const response=await fetch("/api/activities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,topic,level,identityMode:mode,studentCount:actualStudents,roster,questions})});const data=await response.json() as {id?:string;error?:string};if(!response.ok||!data.id)throw new Error(data.error||"The activity could not be published.");setPublishedUrl(`${window.location.origin}/activity/${data.id}`)}catch(e){setError(e instanceof Error?e.message:"The activity could not be published.")}finally{setPublishing(false)}}
return <main className="teacherPage"><header className="topbar"><div className="brand"><span className="brandMark">QB</span><span>Question Builder</span></div><span className="classTag">TEACHER SETUP</span></header><section className="teacherHero"><p className="eyebrow">ONE CLASS · ONE LINK</p><h1>Build the questions.<br/><em>Share the conversation.</em></h1><p>Create questions for any level, distribute them evenly, and publish one simple page for your students.</p></section><div className="builder">
<section className="panel setupPanel"><div className="step">01</div><div><h2>Set up your activity</h2><p className="muted">The student count and question variety are separate.</p></div><div className="formGrid wide"><label>Activity title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. hobbies, identity, lifelong principles"/></label></div><div className="formGrid"><label>Student level<select value={level} onChange={e=>setLevel(e.target.value as Level)}>{Object.keys(levelNotes).map(item=><option key={item}>{item}</option>)}</select><small>{levelNotes[level]}</small></label><label>Number of students<input type="number" min="1" max="300" value={studentCount} disabled={mode==="roster"} onChange={e=>setStudentCount(Number(e.target.value))}/></label><label>Different questions<input type="number" min="1" max="50" value={variety} onChange={e=>setVariety(Number(e.target.value))}/></label></div><button className="primary" onClick={()=>setQuestions(makeQuestions(topic,level,Math.max(1,variety)))}>Suggest {variety} questions</button></section>
<section className="panel"><div className="panelHead"><div><div className="step">02</div><h2>Review the questions</h2><p className="muted">Suggestions are a starting point. You have final control.</p></div><div className="tools"><button onClick={()=>setQuestions(q=>[...q,{text:"",hint:""}])}>+ Add</button><button onClick={()=>setQuestions(items=>[...items].sort(()=>Math.random()-.5))}>Shuffle</button></div></div><div className="questionList">{questions.map((q,i)=><article className="questionEditor" key={i}><div className="questionIndex">Q{String(i+1).padStart(2,"0")}</div><label>Question<textarea value={q.text} onChange={e=>updateQuestion(i,"text",e.target.value)}/></label><label>Optional hint<textarea className="hintInput" value={q.hint} onChange={e=>updateQuestion(i,"hint",e.target.value)} placeholder="Vocabulary, sentence starter, examples, or thinking support"/></label><div className="editorActions"><button onClick={()=>{const replacement=makeQuestions(topic,level,Math.max(i+1,variety))[i];setQuestions(items=>items.map((item,x)=>x===i?replacement:item))}}>Suggest again</button><button className="danger" onClick={()=>setQuestions(items=>items.filter((_,x)=>x!==i))}>Remove</button></div></article>)}</div></section>
<section className="panel"><div className="step">03</div><h2>Choose how students identify themselves</h2><div className="modeSwitch"><button className={mode==="number"?"active":""} onClick={()=>setMode("number")}><b>Student numbers</b><span>Students choose 1–{studentCount}</span></button><button className={mode==="roster"?"active":""} onClick={()=>setMode("roster")}><b>Roster names</b><span>Students choose their registered name</span></button></div>{mode==="roster"&&<label className="rosterLabel">Paste names — one per line or separated by commas<textarea value={rosterText} onChange={e=>setRosterText(e.target.value)} placeholder={"Akari Sato\nHaruto Suzuki\nMei Tanaka"}/><small>{roster.length} students found</small></label>}<div className="assignmentSummary"><b>{actualStudents||0} students</b><span>← evenly assigned →</span><b>{questions.length} questions</b><p>{actualStudents>0&&questions.length>0?`Each question will go to about ${Math.floor(actualStudents/questions.length)}–${Math.ceil(actualStudents/questions.length)} students.`:"Add students and questions to preview the distribution."}</p></div></section>
<section className="publishPanel"><div><p className="eyebrow">READY TO SHARE?</p><h2>Publish one student page</h2><p>Students can choose their number or name and freely review the other questions.</p></div><button className="publishButton" onClick={publish} disabled={publishing}>{publishing?"Publishing…":"Publish activity →"}</button>{error&&<p className="error">{error}</p>}{publishedUrl&&<div className="success"><b>Your student page is ready</b><a href={publishedUrl}>{publishedUrl}</a><div><button onClick={()=>navigator.clipboard.writeText(publishedUrl)}>Copy link</button><a className="openLink" href={publishedUrl}>Open student page →</a></div></div>}</section>
</div><footer><span>QUESTION BUILDER</span><span>Any topic. Any level. One shared page.</span></footer></main>}
