"use client";
import {useEffect,useMemo,useState} from "react";
import QRCode from "qrcode";
type Question={id:string;text:string;followUp:string;hint:string;grammarTag:string};
const levels=["A1 (Starter)","A2 (Elementary)","B1 (Intermediate)","B2–C1 (Advanced)"];
function parseRoster(value:string){return value.split(/[\n,]+/).map(n=>n.trim()).filter(Boolean)}
function encodeActivity(value:unknown){const bytes=new TextEncoder().encode(JSON.stringify(value));let binary="";bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
export default function TeacherPage(){
  const[title,setTitle]=useState("Conversation Scavenger Hunt"),[topic,setTopic]=useState("Favorite things"),[level,setLevel]=useState(levels[1]),[studentCount,setStudentCount]=useState(40),[variety,setVariety]=useState(10),[mode,setMode]=useState<"number"|"roster">("number"),[rosterText,setRosterText]=useState(""),[questions,setQuestions]=useState<Question[]>([]),[busy,setBusy]=useState(false),[publishedUrl,setPublishedUrl]=useState(""),[error,setError]=useState(""),[qrDataUrl,setQrDataUrl]=useState(""),[activityCode,setActivityCode]=useState("");
  const roster=useMemo(()=>parseRoster(rosterText),[rosterText]),actualStudents=mode==="roster"?roster.length:studentCount;
  useEffect(()=>{if(!publishedUrl){setQrDataUrl("");return}let cancelled=false;QRCode.toDataURL(publishedUrl,{width:320,margin:1}).then(url=>{if(!cancelled)setQrDataUrl(url)}).catch(()=>{if(!cancelled)setQrDataUrl("")});return()=>{cancelled=true}},[publishedUrl]);
  const update=(i:number,field:keyof Question,value:string)=>setQuestions(items=>items.map((item,x)=>x===i?{...item,[field]:value}:item));
  async function suggest(count=variety,replaceIndex?:number){setBusy(true);setError("");try{const response=await fetch("/api/generate-questions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({topic,level,count,followUps:true,includeHints:true})});const data=await response.json() as {items?:Question[];error?:string};if(!response.ok||!data.items?.length)throw new Error(data.error||"No questions were generated.");if(replaceIndex===undefined)setQuestions(data.items.map((q,i)=>({...q,id:`q${i+1}`})));else setQuestions(items=>items.map((q,i)=>i===replaceIndex?{...data.items![0],id:q.id}:q))}catch(e){setError(e instanceof Error?e.message:"Question generation failed.")}finally{setBusy(false)}}
  async function createLink(){setError("");setActivityCode("");const approved=questions.filter(q=>q.text.trim()).map((q,i)=>({...q,id:`q${i+1}`}));if(!title.trim()||!approved.length||actualStudents<1){setError("Add a title, students, and approved questions first.");return}const payload={version:1,title,topic,level,identityMode:mode,studentCount:actualStudents,roster:mode==="roster"?roster:[],questions:approved};setPublishedUrl(`${window.location.origin}/activity#data=${encodeActivity(payload)}`);try{const response=await fetch("/api/activities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {code?:string};if(response.ok&&data.code)setActivityCode(data.code)}catch{}}
  return <main className="teacherPage"><header className="topbar"><div className="brand"><span className="brandMark">QB</span><span>Question Builder</span></div><span className="classTag">TEACHER SETUP</span></header><section className="teacherHero"><p className="eyebrow">ONE CLASS · ONE LINK</p><h1>Build the questions.<br/><em>Share the conversation.</em></h1><p>Create natural questions for any level, approve them, and share one self-contained student page.</p></section><div className="builder">
    <section className="panel setupPanel"><div className="step">01</div><div><h2>Set up your activity</h2><p className="muted">Class size and question variety are separate.</p></div><div className="formGrid wide"><label>Activity title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Favorite things, travel, lifelong principles"/></label></div><div className="formGrid"><label>Student level<select value={level} onChange={e=>setLevel(e.target.value)}>{levels.map(item=><option key={item}>{item}</option>)}</select></label><label>Number of students<input type="number" min="1" max="300" value={studentCount} disabled={mode==="roster"} onChange={e=>setStudentCount(Number(e.target.value))}/></label><label>Different questions<input type="number" min="1" max="20" value={variety} onChange={e=>setVariety(Number(e.target.value))}/></label></div><button className="primary" disabled={busy} onClick={()=>suggest()}>{busy?"Creating natural questions…":`Suggest ${variety} questions`}</button>{error&&<p className="errorInline">{error}</p>}</section>
    <section className="panel"><div className="panelHead"><div><div className="step">02</div><h2>Review the questions</h2><p className="muted">The generator suggests; the teacher approves.</p></div><div className="tools"><button onClick={()=>setQuestions(q=>[...q,{id:`q${q.length+1}`,text:"",followUp:"",hint:"",grammarTag:""}])}>+ Add</button><button onClick={()=>setQuestions(items=>[...items].sort(()=>Math.random()-.5).map((q,i)=>({...q,id:`q${i+1}`})))}>Shuffle</button></div></div>{!questions.length?<div className="emptyQuestions">Enter a topic and select “Suggest questions.”</div>:<div className="questionList">{questions.map((q,i)=><article className="questionEditor" key={q.id}><div className="questionIndex">{q.id.toUpperCase()}</div><label>Question<textarea value={q.text} onChange={e=>update(i,"text",e.target.value)}/></label><div className="supportFields"><label>Optional follow-up<textarea value={q.followUp} onChange={e=>update(i,"followUp",e.target.value)}/></label><label>Optional hint<textarea className="hintInput" value={q.hint} onChange={e=>update(i,"hint",e.target.value)}/></label></div><div className="editorActions"><button disabled={busy} onClick={()=>suggest(1,i)}>Suggest again</button><button className="danger" onClick={()=>setQuestions(items=>items.filter((_,x)=>x!==i).map((item,x)=>({...item,id:`q${x+1}`})))}>Remove</button></div></article>)}</div>}</section>
    <section className="panel"><div className="step">03</div><h2>Choose student identification</h2><div className="modeSwitch"><button className={mode==="number"?"active":""} onClick={()=>setMode("number")}><b>Student numbers</b><span>Students choose 1–{studentCount}</span></button><button className={mode==="roster"?"active":""} onClick={()=>setMode("roster")}><b>Roster names</b><span>Students choose a registered name</span></button></div>{mode==="roster"&&<label className="rosterLabel">Paste names — one per line or separated by commas<textarea value={rosterText} onChange={e=>setRosterText(e.target.value)} placeholder={"Akari Sato\nHaruto Suzuki\nMei Tanaka"}/><small>{roster.length} students found</small></label>}<div className="assignmentSummary"><b>{actualStudents||0} students</b><span>← assigned by ID →</span><b>{questions.length} questions</b><p>No individual assignment records are stored. Student position determines the question ID.</p></div></section>
    <section className="publishPanel"><div><p className="eyebrow">READY TO SHARE?</p><h2>Create the student link</h2><p>The approved activity and question IDs travel inside one link—no assignment database.</p></div><button className="publishButton" onClick={createLink}>Create student link →</button>{publishedUrl&&<div className="success"><b>Your self-contained student page is ready</b>{qrDataUrl&&<div className="qrBlock"><span>SCAN TO JOIN</span><img className="qrCode" src={qrDataUrl} alt="QR code that opens this activity" width={240} height={240}/></div>}{activityCode&&<div className="activityCodeBlock"><span>ACTIVITY CODE</span><b className="activityCodeValue">{activityCode}</b><small>Students can enter this at /join</small></div>}<a href={publishedUrl}>{publishedUrl}</a><div><button onClick={()=>navigator.clipboard.writeText(publishedUrl)}>Copy link</button><a className="openLink" href={publishedUrl}>Open student page →</a></div></div>}</section>
  </div><footer><span>QUESTION BUILDER</span><span>Natural questions · Simple delivery</span></footer></main>
}
